<?php

namespace SMS\AdministrativeBundle\Repository;

/**
 * AttendanceProfessorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceProfessorRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * Get Attendance By Date and Session and User
     *
     * @param date $date
     * @param Session $session
     * @param Student $professor
     * @return array
     */
	public function findByDateAndSessionAndUser($attendance)
	{
		return $this->createQueryBuilder('attendance')
				->join('attendance.session', 'session')
				->join('attendance.professor', 'professor')
				->where("attendance.date = :date")
				->andWhere('session.id = :session')
				->andWhere('professor.id = :professor')
				->setParameter('date', $attendance->getDate(), \Doctrine\DBAL\Types\Type::DATE)
				->setParameter('professor', $attendance->getProfessor()->getId())
				->setParameter('session', $attendance->getSession()->getId())
				->getQuery()
            	->getOneOrNullResult();
	}
}
