<?php

namespace SMS\AdministrativeBundle\Repository;

/**
 * AttendanceSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceSectionRepository extends \Doctrine\ORM\EntityRepository
{
		/**
		 * Get Attendance By Date and Session and User
		 *œ
		 * @param date $date
		 * @param Session $session
		 * @param Student $student
		 * @return array
		 */
		public function findByDateAndSessionAndSection($date, $session, $section)
		{
				return $this->createQueryBuilder('attendance')
								->join('attendance.session', 'session')
								->join('attendance.section', 'section')
								->where("attendance.date = :date")
								->andWhere('session.id = :session')
								->andWhere('section.id = :section')
								->setParameter('date', $date , \Doctrine\DBAL\Types\Type::DATE)
								->setParameter('section', $section)
								->setParameter('session', $session)
								->getQuery()
								->getOneOrNullResult();
		}

		/**
		 * Get Attendance By Section
		 *
		 * @param Section $section
		 * @return array
		 */
		public function findStatsBySection($section)
		{
				return $this->createQueryBuilder('attendance')
									->select("attendanceStudent.status as name, attendance.date AS date, count(attendanceStudent.id) as value")
									->join('attendance.attendanceStudent', 'attendanceStudent')
									->join('attendance.section', 'section')
									->where('section.id = :section')
									->setParameter('section', $section->getId())
									->groupBy('name , date')
									->getQuery()
					        ->getResult();
		}

		/**
		 * Get Attendance By Section
		 *
		 * @param Section $student
		 * @return array
		 */
		public function findStatsByStudent($student)
		{
				return $this->createQueryBuilder('attendance')
									->select("attendanceStudent.status as name, attendance.date AS date, count(attendanceStudent.id) as value")
                  ->join('attendance.attendanceStudent', 'attendanceStudent')
									->join('attendanceStudent.student', 'student')
									->where('student.id = :student')
									->setParameter('student', $student->getId())
									->groupBy('name , date')
									->getQuery()
					        ->getResult();
		}

}
