<?php

namespace SMS\StudyPlanBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SMS\StudyPlanBundle\Entity\Session;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends EntityRepository
{

	/**
     * Get Exam By Course
     *
     * @param integer $course
     * @return array
     */
	public function findByCourse($course)
	{
		return $this->createQueryBuilder('exam')
				->join('exam.course', 'course')
				->andWhere('course.id = :course')
				->setParameter('course', $course)
				->getQuery()
				->getResult();
	}
	/**
     * Get Exam By StartDate And EndDate
     *
     * @param \DateTime $startDate
     * @param \DateTime $endDate
     * @return array
     */
	public function findByStartDateAndEndDate($startDate , $endDate, $section)
	{
		return $this->createQueryBuilder('exam')
				->select("exam.examName as title ,course.coefficient, course.courseName, typeExam.typeExamName  , DATE_FORMAT(exam.startTime ,'%H:%m') as startTime , DATE_FORMAT(exam.endTime ,'%H:%m') as endTime")
				->addSelect("DATE_FORMAT(exam.dateExam ,'%Y-%m-%d') as date")
				->join('exam.course', 'course')
				->join('exam.typeExam', 'typeExam')
				->where('exam.dateExam BETWEEN :startDate AND :endDate')
				->andWhere(':section MEMBER OF exam.section')
   			->setParameter('startDate', $startDate->format('Y-m-d'))
   			->setParameter('endDate', $endDate->format('Y-m-d'))
				->setParameter('section',  $section)
				->getQuery()
				->getResult();
	}
}
