<?php

namespace SMS\StudyPlanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
	/**
     * Get Note By ids
     *
     * @param SMS\StudyPlanBundle\Entity\Exam $ids
     * @param SMS\UserBundle\Entity\Student $ids
     * @return array
     */
	public function findByExamAndStudent($exam , $student)
	{
		return $this->createQueryBuilder('note')
				->join('note.student', 'student')
				->join('note.exam', 'exam')
				->Where('exam.id = :exam')
				->andWhere('student.id = :student')
				->setParameter('exam', $exam->getId())
				->setParameter('student', $student->getId())
				->getQuery()
            	->getOneOrNullResult();
	}
}
