<?php

namespace SMS\StoreBundle\Repository;

/**
 * OrderProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
