<?php

namespace SMS\StoreBundle\Repository;

/**
 * StoreOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreOrderRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * Get order By reference
   *
   * @param String $reference
   * @return array
   */
    public function findOrderByRefrence($reference)
    {
        return $this->createQueryBuilder('u')
            ->where('u.reference = :reference')
            ->setParameter('reference', $reference)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
