<?php

namespace SMS\SchoolBundle\Repository;

/**
 * PricingFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingFeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
