<?php

namespace SMS\SchoolBundle\Repository;

/**
 * TestimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolTestimonialRepository extends \Doctrine\ORM\EntityRepository
{
}
