<?php

namespace SMS\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SMS\UserBundle\Entity\User;
/**
 * ProfessorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessorRepository extends EntityRepository
{
	/**
     * @param string[] $criteria format: array('user' => <user_id>, 'name' => <name>)
     */
    public function findByUniqueCriteria(array $criteria)
    {
        // would use findOneBy() but Symfony expects a Countable object
        return $this->_em->getRepository(User::class)->findBy($criteria);
    }

		/**
	 * find All Professor By establishment
	 * @param SMS\EstablishmentBundle\Entity\Establishment $establishment
	 * @return array
	 */
	public function findAllProfessorByEstablishment($establishment)
	{
			$query = $this->createQueryBuilder('professor')
				->join('professor.establishment', 'establishment')
				->where('establishment.id = :establishment')
				->setParameter('establishment', $establishment->getId());
			return $query;
	}

	/**
	 * Get professors By establishment
	 *
	 * @param integer $establishment
	 * @return array
	 */
	public function findStatsByEstablishment($establishment)
	{
			return $this->createQueryBuilder('professor')
							->select("Count(professor) as value , professor.gender as name")
							->join('professor.establishment', 'establishment')
							->andWhere('establishment.id = :establishment')
							->setParameter('establishment', $establishment->getId())
							->groupBy('name')
							->getQuery()
							->getResult();
	}
}
