<?php

namespace SMS\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SMS\UserBundle\Entity\User;
use Doctrine\ORM\Query;
/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    /**
     * @param string[] $criteria format: array('user' => <user_id>, 'name' => <name>)
     */
    public function findByUniqueCriteria(array $criteria)
    {
        // would use findOneBy() but Symfony expects a Countable object
        return $this->_em->getRepository(User::class)->findBy($criteria);
    }

      /**
     * Get All registred users
     *
     * @return array
     */
    public function findAllRegistredStudent()
    {
        $query = $this->createQueryBuilder('student')
          ->join('student.registrations', 'registrations')
          ->join('registrations.paymentType', 'paymentType')
          ->select("partial student.{id ,imageName , username , firstName , lastName , phone , email}")
          ->distinct('student.id');
        return $query;
    }

    /**
     * Get Student By Section And establishment
     *
     * @param integer $section
     * @return array
     */
    public function findBySectionAndEstablishment($section, $establishment)
    {
        return $this->createQueryBuilder('student')
                ->join('student.section', 'section')
                ->join('student.establishment', 'establishment')
                ->andWhere('section.id = :section')
                ->setParameter('section', $section)
                ->andWhere('establishment.id = :establishment')
                ->setParameter('establishment', $establishment)
                ->getQuery()
                ->getResult();
    }
}
