<?php

namespace SMS\EstablishmentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DivisionRepository extends EntityRepository
{
	/**
     * @return Query
     */
    public function findAll()
    {
        return $this->createQueryBuilder('f');
    }

    /**
     * @param String $field
     * @return Query
     */
    public function findByAnything($field)
    {
        return $this->createQueryBuilder('f')
        			->Where('f.name LIKE :search OR f.startDate LIKE :search OR f.endDate LIKE :search')
                	->setParameter('search', '%'.$field.'%')
                	->orderBy('f.id', 'ASC');
    }
}
