<?php

namespace SMS\EstablishmentBundle\Repository;

/**
 * EstablishmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablishmentRepository extends \Doctrine\ORM\EntityRepository
{
}
