<?php

namespace SMS\PaymentBundle\Repository;

/**
 * CatchUpLessonSechduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatchUpLessonSechduleRepository extends \Doctrine\ORM\EntityRepository
{
}
