<?php

namespace SMS\PaymentBundle\Repository;

/**
 * dddRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dddRepository extends \Doctrine\ORM\EntityRepository
{
}
