<?php

namespace SMS\PaymentBundle\Repository;

/**
 * RegistrationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
