<?php

namespace SMS\PaymentBundle\Repository;

/**
 * TypePaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
